### ISSUE TITLE
TypeError: Cannot create new instances of type 'Labels'

### ISSUE THREAD

**Issue by shreyas29** [TronicLT/action_bank#1]
When I compile the "ab_ucf50_svm.py" file, I am getting the following error:

Traceback (most recent call last):

  File "ab_ucf50_svm.py", line 81, in <module>
    ab_svm.kfoldcv_svm(D,Y,10,cores=1,innerCores=8,useLibLinear=True,useL1R=False)

  File "/home/shreyas/Software_Libraries/action_bank/base/ab_svm.py", line 102, in kfoldcv_svm
    kfoldcv_svm_aux(j, k, Dk, Yk, innerCores, useLibLinear, useL1R)

  File "/home/shreyas/Software_Libraries/action_bank/base/ab_svm.py", line 71, in kfoldcv_svm_aux
    res = SVMLinear(Di, np.int32(Yi), Dt, threads=threads, useLibLinear=useLibLinear, useL1R=useL1R)

  File "/home/shreyas/Software_Libraries/action_bank/base/ab_svm.py", line 275, in SVMLinear
    labels = Labels(np.float64(tlabs))

TypeError: Cannot create new instances of type 'Labels'

**Comment by TronicLT** [comment]
I got the code from [Action Bank](http://www.cse.buffalo.edu/~jcorso/r/actionbank/). I also had issues running the code in the scripts folder. I found that most of my problems had to do with [shogun's](http://www.shogun-toolbox.org/) API changes. So I mainly used [actionbank.py](https://github.com/TronicLT/action_bank/blob/master/base/actionbank.py) to generate the banks, and [load_data.py](https://github.com/TronicLT/action_bank/blob/master/base/load_data.py) to read the action banks for the specific datasets. To recreate their experiments I used [sklearn](http://scikit-learn.org/) library.

Hope that helps.

**Comment by shreyas29** [comment]
If I am using BinaryLabels(np.float64(tlabs)) instead of Labels(np.float64(tlabs)), then it's working fine. But I don't know whether it's correct or not. 

Between Thanks for sharing this code, integrated with shogun 4. I was unable to compile the code downloaded from [Action Bank](http://www.cse.buffalo.edu/~jcorso/r/actionbank/) as it was using older version of shogun.
